#!/bin/sh

mkdir /usr/share/whiteprocess
python2.7 -m compileall source/
mv -v source/*.pyc /usr/share/whiteprocess/
echo 'S,0' > /usr/share/whiteprocess/whiteprocess.status
cp -v source/whiteprocess.conf /usr/share/whiteprocess/
cp -v source/whiteprocess.conf /etc/
cp -v source/whiteprocess /bin/whiteprocess
chmod +x /bin/whiteprocess
echo ''
echo 'whiteprocess installed.'
