#!/bin/sh

mkdir /usr/share/whiteprocess
cp source/whiteprocess.py /usr/share/whiteprocess/whiteprocess.py
cp source/whiteprocess.conf /etc/whiteprocess.conf
cp source/whiteprocess /bin/whiteprocess
chmod +x /bin/whiteprocess
echo whiteprocess installed.
